export const alternative = [
  {
    id: 1,
    name: "french press",
    cost: 100,
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USsssA",
      capacity: "4 cup",
      virtues: "",
    },
    img: require("@/components/common/img/alts/french(1).jpg"),
  },
  {
    id: 2,
    name: "french press",
    cost: 200,
    img: require("@/components/common/img/alts/french(2).jpg"),
    description: {
      weight: "300g",
      material: "metal",
      manufacturer: "China",
      capacity: "5 cup",
      virtues: "",
    },
  },
  {
    id: 3,
    name: "french press",
    cost: 200,
    img: require("@/components/common/img/alts/french(3).jpg"),
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
      virtues: "",
    },
  },
  {
    id: 4,
    name: "french press",
    cost: 200,
    img: require("@/components/common/img/alts/french(4).jpg"),
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
      virtues: "",
    },
  },
  {
    id: 5,
    name: "french press",
    cost: 200,
    img: require("@/components/common/img/alts/french(5).jpg"),
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
      virtues: "",
    },
  },
  {
    id: 6,
    name: "french press",
    cost: 200,
    img: require("@/components/common/img/alts/french(6).jpg"),
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
      virtues: "",
    },
  },
  {
    id: 7,
    name: "french press",
    cost: 200,
    img: require("@/components/common/img/alts/french(7).jpg"),
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
      virtues: "",
    },
  },
  {
    id: 8,
    name: "french press",
    cost: 200,
    img: require("@/components/common/img/alts/french(8).jpg"),
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
      virtues: "",
    },
  },
  {
    id: 9,
    name: "french press",
    cost: 200,
    img: require("@/components/common/img/alts/french(9).jpg"),
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
      virtues: "",
    },
  },
  {
    id: 10,
    name: "french press",
    cost: 200,
    img: require("@/components/common/img/alts/french(10).jpg"),
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
      virtues: "",
    },
  },
  {
    id: 11,
    name: "french press",
    cost: 200,
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
      virtues: "",
    },
    img: require("@/components/common/img/alts/french(11).jpg"),
  },
  {
    id: 12,
    name: "french press",
    cost: 200,
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
      virtues: "",
    },
    img: require("@/components/common/img/alts/french(12).jpg"),
  },
  {
    id: 13,
    name: "Kermes",
    cost: 200,
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
      virtues: "",
    },
    img: require("@/components/common/img/alts/kermes(1).png"),
  },
  {
    id: 14,
    name: "Kermes",
    cost: 200,
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
      virtues: "",
    },
    img: require("@/components/common/img/alts/kermes(2).jpg"),
  },
  {
    id: 15,
    name: "Kermes",
    cost: 200,
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
      virtues: "",
    },
    img: require("@/components/common/img/alts/kermes(3).png"),
  },
  {
    id: 16,
    name: "Kermes",
    cost: 200,
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
      virtues: "",
    },
    img: require("@/components/common/img/alts/kermes(4).jpg"),
  },
  {
    id: 17,
    name: "purover",
    cost: 20,
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
      virtues: "",
    },
    img: require("@/components/common/img/alts/purover(1).jpg"),
  },
  {
    id: 18,
    name: "purover",
    cost: 400,
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
      virtues: "",
    },
    img: require("@/components/common/img/alts/purover(2).jpg"),
  },
  {
    id: 19,
    name: "purover",
    cost: 60,
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
      virtues: "",
    },
    img: require("@/components/common/img/alts/purover(3).jpg"),
  },
  {
    id: 20,
    name: "purover",
    cost: 40,
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
      virtues: "",
    },
    img: require("@/components/common/img/alts/purover(4).jpg"),
  },
  {
    id: 22,
    name: "purover",
    cost: 47,
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
      virtues: "",
    },
    img: require("@/components/common/img/alts/purover(5).jpg"),
  },
];
export const machine = [
  {
    id: 300,
    name: "Saeco Spidem Trevi Chiara",
    cost: 168,
    description: {
      brand: "SAECO",
      weight: "8.5 kg",
      sizes: "337 х 377 х 325",
      power: "1250 W",
      waterTank: "1.8",
      manufacturer: "USA",
      virtues:
        "Automatic espresso coffee machine. Only coffee beans are used. Button control panel, LED display. Coffee grinder with adjustable grinding quality. Manual adjustment of the volume of water per serving. Removable central brewing device. Height-adjustable telescopic dispenser. Making two cups at the same time. Tube for serving hot water and steam. Panarello nozzle for the preparation of milk foam. Case material: ABS plastic. Swivel base",
    },
    img: require("@/components/common/img/machine/machine(7).jpg"),
  },
  {
    id: 301,
    name: "PHILIPS-SAECO Vienna Digital",
    cost: 171,
    description: {
      brand: "SAECO",
      weight: "8.5 kg",
      sizes: "325 х 377 х 337",
      power: "1250 W",
      waterTank: "2",
      manufacturer: "China",
      virtues:
        "Automatic espresso coffee machine with display. Only coffee beans are used. Button control panel, LED indication. Coffee grinder with adjustable grinding quality. Manual adjustment of the amount of water per serving. Removable central brewing device. Height-adjustable telescopic dispenser. Making two cups at the same time. Tube for hot water and steam supply. Panarello nozzle for making milk foam. Case material: ABS plastic. Swivel base",
    },
    img: require("@/components/common/img/machine/machine(8).jpg"),
  },
  {
    id: 302,
    name: "PHILIPS-SAECO Royal Office",
    cost: 204,
    description: {
      brand: "SAECO",
      weight: "17.5 kg",
      sizes: "380 х 460 х 440",
      power: "2000 W",
      waterTank: "6.2",
      manufacturer: "China",
      virtues:
        "Hoppers for water and coffee of large volume. All the opening parts are “locked” (restrict access to personnel). Possibility to connect a coin / token acceptor. Possibility of installation on a pedestal (food storage / discharge of cake directly into garbage bags). Boiler material: stainless steel. Case material: ABS / metal plastic. The coffee machine is not designed to work with milk. The coffee machine can only prepare one serving of the drink at a time",
    },
    img: require("@/components/common/img/machine/machine(5).jpg"),
  },
  {
    id: 303,
    name: "PHILIPS-SAECO Royal Professional",
    cost: 330,
    description: {
      brand: "SAECO",
      weight: "1.5 kg",
      sizes: "455 х 390 х 395",
      power: "2000 W",
      waterTank: "2.4",
      manufacturer: "Italy",
      virtues:
        "Type of coffee machine: automatic espresso coffee machine. Coffee grinder with adjustable grinding quality. Used coffee type: coffee beans, ground coffee. Control system: push-button with display. Removable central brewing device. Cappuccino preparation: external professional cappuccino machine. Productivity: 120 servings of coffee per hour",
    },
    img: require("@/components/common/img/machine/machine(6).jpg"),
  },
  {
    id: 304,
    name: "La Spaziale Nuova",
    cost: 1100,
    description: {
      brand: "La Spaziale",
      weight: "20 kg",
      sizes: "570 х 465 х 530",
      power: "3000 W",
      waterTank: "2.4",
      manufacturer: "Italy",
      virtues: "",
    },
    img: require("@/components/common/img/machine/machine(9).jpg"),
  },
  {
    id: 305,
    name: "MCE NEW START AEP/1",
    cost: 1980,
    description: {
      brand: "MCE",
      weight: "52 kg",
      sizes: "490 х 535 х 535",
      power: "2000-2700 W",
      waterTank: "6",
      manufacturer: "Italy",
      virtues: "",
    },
    img: require("@/components/common/img/machine/machine(10).jpg"),
  },
  {
    id: 306,
    name: "MCE NEW START SAE/1",
    cost: 2100,
    description: {
      brand: "MCE",
      weight: "52 kg",
      sizes: "490 х 535 х 535",
      power: "2000-2700 W",
      waterTank: "6",
      manufacturer: "Italy",
      virtues: "",
    },
    img: require("@/components/common/img/machine/machine(2).jpg"),
  },
  {
    id: 307,
    name: "BARISTA PRO 1 GR",
    cost: 3500,
    description: {
      brand: "ASCASO",
      weight: "45 kg",
      sizes: "404 х 535 х 465",
      power: "2000 W",
      waterTank: "6",
      manufacturer: "Spain",
      virtues: "",
    },
    img: require("@/components/common/img/machine/machine(1).jpg"),
  },
  {
    id: 308,
    name: "BARISTA PRO 2 GR",
    cost: 4000,
    description: {
      brand: "ASCASO",
      weight: "71 kg",
      sizes: "404 х 535 х 465",
      power: "3500 W",
      waterTank: "13",
      manufacturer: "Spain",
      virtues: "",
    },
    img: require("@/components/common/img/machine/machine(3).jpg"),
  },
  {
    id: 309,
    name: "BARISTA PRO 3 GR",
    cost: 4693,
    description: {
      brand: "ASCASO",
      weight: "93 kg",
      sizes: "929 х 535 х 465",
      power: "5550 W",
      waterTank: "18",
      manufacturer: "Spain",
      virtues: "",
    },
    img: require("@/components/common/img/machine/machine(11).jpg"),
  },
];
export const keepCup = [
  {
    id: 200,
    name: "Original Alchemy Hermes Medium",
    cost: 18.33,
    description: {
      height: "134",
      material: "Silicone",
      manufacturer: "Australia",
      capacity: "354 ml",
      virtues:
        "A tight-fitting lid protects you from splashing the drink. A fresh, restrained and incredibly stylish design. A convenient valve reliably closes the drinking hole. A convenient silicone rim protects your hand from burns and prevents the glass from slipping. The plastic used is non-toxic and safe for health. Can be washed in a dishwasher. and heat in the microwave (without lid)",
    },
    img: require("@/components/common/img/keepcup/keepcup(1).jpg"),
  },
  {
    id: 201,
    name: "Original Alchemy Hermes Large",
    cost: 20,
    description: {
      height: "234",
      material: "Silicone",
      manufacturer: "Australia",
      capacity: "500 ml",
      virtues:
        "A tight-fitting lid protects you from splashing the drink. A fresh, restrained and incredibly stylish design. A convenient valve reliably closes the drinking hole. A convenient silicone rim protects your hand from burns and prevents the glass from slipping. The plastic used is non-toxic and safe for health. Can be washed in a dishwasher. and heat in the microwave (without lid)",
    },
    img: require("@/components/common/img/keepcup/keepcup(2).jpg"),
  },
  {
    id: 202,
    name: "Original Alchemy Hermes Small",
    cost: 20,
    description: {
      height: "91",
      material: "Silicone",
      manufacturer: "Australia",
      capacity: "227 ml",
      virtues:
        "A tight-fitting lid protects you from splashing the drink. A fresh, restrained and incredibly stylish design. A convenient valve reliably closes the drinking hole. A convenient silicone rim protects your hand from burns and prevents the glass from slipping. The plastic used is non-toxic and safe for health. Can be washed in a dishwasher. and heat in the microwave (without lid)",
    },
    img: require("@/components/common/img/keepcup/keepcup(9).jpg"),
  },
  {
    id: 203,
    name: "«Day Break» XS",
    cost: 25,
    description: {
      height: "75",
      material: "Silicone",
      manufacturer: "USA",
      capacity: "120 ml",
      virtues:
        "Stylish, lightweight, reusable plastic mug. The cheerful design of the kipkap resembles an appetizing strawberry in chocolate. The kipkap will allow you to comfortably hold a glass, even if it has a very hot drink. KeepCup produce glasses and advocate for nature, urging you to refuse to use paper cups",
    },
    img: require("@/components/common/img/keepcup/keepcup(4).jpg"),
  },
  {
    id: 204,
    name: "Original Alchemy Antimony Medium",
    cost: 19,
    description: {
      height: "111",
      material: "Silicone",
      manufacturer: "Australia",
      capacity: "340 ml",
      virtues:
        "A tight-fitting lid protects you from splashing the drink. A fresh, restrained and incredibly stylish design. A convenient valve reliably closes the drinking hole. A convenient silicone rim protects your hand from burns and prevents the glass from slipping. The plastic used is non-toxic and safe for health. Can be washed in a dishwasher. and heat in the microwave (without lid)",
    },
    img: require("@/components/common/img/keepcup/keepcup(3).jpg"),
  },
  {
    id: 205,
    name: "Brew Alchemy Potion Medium",
    cost: 19.5,
    description: {
      height: "111",
      material: "glass",
      manufacturer: "Australia",
      capacity: "340 ml",
      virtues:
        "Heat-resistant thermo-glass. Glass-coated kapkap with a silicone rim. Soothing and mysterious design. A tightly frayed lid prevents the liquid from splashing inside on the go. A rotary valve closing the hole for drinking. To create a glass, plastic without harmful Bisphenol-A impurities is used",
    },
    img: require("@/components/common/img/keepcup/keepcup(7).jpg"),
  },
  {
    id: 206,
    name: "Brew Alchemy Magic Small",
    cost: 19.5,
    description: {
      height: "91",
      material: "glass",
      manufacturer: "Australia",
      capacity: "227 ml",
      virtues:
        "Heat-resistant thermo-glass. Glass-coated kapkap with a silicone rim. Soothing and mysterious design. A tightly frayed lid prevents the liquid from splashing inside on the go. A rotary valve closing the hole for drinking. To create a glass, plastic without harmful Bisphenol-A impurities is used",
    },
    img: require("@/components/common/img/keepcup/keepcup(8).jpg"),
  },
  {
    id: 207,
    name: "Brew Cork Press» Small",
    cost: 26,
    description: {
      height: "91",
      material: "glass",
      manufacturer: "Australia",
      capacity: "227 ml",
      virtues:
        "Heat-resistant thermo-glass. Glass-coated kapkap with a silicone rim. Soothing and mysterious design. A tightly frayed lid prevents the liquid from splashing inside on the go. A rotary valve closing the hole for drinking. To create a glass, plastic without harmful Bisphenol-A impurities is used",
    },
    img: require("@/components/common/img/keepcup/keepcup(6).jpg"),
  },
  {
    id: 208,
    name: "Brew Cork Filter» Medium",
    cost: 26,
    description: {
      height: "95",
      material: "glass",
      manufacturer: "Australia",
      capacity: "340 ml",
      virtues:
        "Heat-resistant thermo-glass. Glass-coated kapkap with a silicone rim. Soothing and mysterious design. A tightly frayed lid prevents the liquid from splashing inside on the go. A rotary valve closing the hole for drinking. To create a glass, plastic without harmful Bisphenol-A impurities is used",
    },
    img: require("@/components/common/img/keepcup/keepcup(5).jpg"),
  },
];
export const coffee = [
  {
    id: 400,
    name: "9 Swans Seasonal Coffee",
    cost: 19,
    description: {
      Size: "12 oz",
      taste: "Milk chocolate, orange, raspberry",
      sourced: "from nariño, colombia",
      elevation: "grown: 1900 meters",
      producers: "amigos de nariño",
      varietals: "caturra, colombia",
      harvested: "summer 2019",
      process: "washed",
      virtues: "",
    },
    img: require("@/components/common/img/coffee/coffee(7).png"),
  },
  {
    id: 401,
    name: "Ethiopia Worka Chelbessa",
    cost: 24,
    description: {
      size: "12 oz",
      taste: "peach, jasmine, pineapple",
      sourced: "gedeb",
      elevation: "1900-2200 meters",
      producers: "smallholder farmers",
      varietals: "jarc selections & landraces",
      harvested: "winter 2020",
      process: "washed",
      virtues: "",
    },
    img: require("@/components/common/img/coffee/coffee(1).png"),
  },
  {
    id: 402,
    name: "Ethiopia Duromina",
    cost: 24,
    description: {
      size: "12 oz",
      taste: "peach, rosewater",
      sourced: "jimma, ethiopia",
      elevation: "2000 meters",
      producers: "small holders",
      varietals: "various landraces",
      harvested: "winter 2020",
      virtues: "",
    },
    img: require("@/components/common/img/coffee/coffee(3).png"),
  },
  {
    id: 403,
    name: "Colombia Jonathan Caicedo",
    cost: 24,
    description: {
      size: "12 oz",
      taste: "limoncello, caramel, rose",
      sourced: "huila",
      elevation: "1800 meters",
      producers: "jonathan caicedo",
      varietals: "caturra",
      harvested: "winter 2020",
      process: "washed",
      virtues: "",
    },
    img: require("@/components/common/img/coffee/coffee(5).png"),
  },
  {
    id: 404,
    name: "Colombia Mireya Trujillo",
    cost: 21,
    description: {
      size: "12 oz",
      taste: "pineapple, vanilla, caramel",
      sourced: "tarqui, huila",
      elevation: "1800 meters",
      producers: "mireya trujillo",
      varietals: "caturra",
      harvested: "winter 2020",
      process: "washed",
      virtues: "",
    },
    img: require("@/components/common/img/coffee/coffee(6).png"),
  },
  {
    id: 405,
    name: "Colombia Jairo Nuñez",
    cost: 21,
    description: {
      size: "12 oz",
      taste: "green apple, mandarin, toffee",
      sourced: "tarqui, huila",
      elevation: "1900 meters",
      producers: "jairo nuñez",
      varietals: "caturra",
      harvested: "winter 2020",
      process: "washed",
      virtues: "",
    },
    img: require("@/components/common/img/coffee/coffee(4).png"),
  },
  {
    id: 406,
    name: "Decaf Colombia",
    cost: 21,
    description: {
      size: "12 oz",
      taste: "cherry, cocoa",
      sourced: "narino, colombia",
      harvested: "summer 2017",
      process: "washed",
      virtues: "",
    },
    img: require("@/components/common/img/coffee/coffee(2).png"),
  },
];
