export const alternative = [
  {
    id: 1,
    name: "pulover1",
    price: 200,
    img: require("@/components/common/img/cer1.jpg"),
  },
  {
    id: 2,
    name: "pulover2",
    price: 200,
    img: require("@/components/common/img/cer2.png"),
  },
  {
    id: 3,
    name: "pulover3",
    price: 200,
    img: require("@/components/common/img/cer3.png"),
  },
  {
    id: 3,
    name: "pulover3",
    price: 200,
    img: require("@/components/common/img/cer3.png"),
  },
  {
    id: 3,
    name: "pulover3",
    price: 200,
    img: require("@/components/common/img/cer3.png"),
  },
  {
    id: 3,
    name: "pulover3",
    price: 200,
    img: require("@/components/common/img/cer3.png"),
  },
  {
    id: 3,
    name: "pulover3",
    price: 200,
    img: require("@/components/common/img/cer3.png"),
  },
  {
    id: 3,
    name: "pulover3",
    price: 200,
    img: require("@/components/common/img/cer3.png"),
  },
  {
    id: 3,
    name: "pulover3",
    price: 200,
    img: require("@/components/common/img/cer3.png"),
  },
  {
    id: 3,
    name: "pulover3",
    price: 200,
    img: require("@/components/common/img/cer3.png"),
  },
  {
    id: 3,
    name: "pulover3",
    price: 200,
    img: require("@/components/common/img/cer3.png"),
  },
  {
    id: 3,
    name: "pulover3",
    price: 200,
    img: require("@/components/common/img/cer3.png"),
  },
  {
    id: 3,
    name: "pulover3",
    price: 200,
    img: require("@/components/common/img/cer3.png"),
  },
  {
    id: 3,
    name: "pulover3",
    price: 200,
    img: require("@/components/common/img/cer3.png"),
  },
  {
    id: 3,
    name: "pulover3",
    price: 200,
    img: require("@/components/common/img/cer3.png"),
  },
  {
    id: 3,
    name: "pulover3",
    price: 200,
    img: require("@/components/common/img/cer3.png"),
  },
  {
    id: 3,
    name: "pulover3",
    price: 200,
    img: require("@/components/common/img/cer3.png"),
  },
];
