export const alternative = [
  {
    id: 1,
    name: "french press",
    cost: 100,
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USsssA",
      capacity: "4 cup",
    },
    img: require("@/components/common/img/alts/french(1).jpg"),
  },
  {
    id: 2,
    name: "french press",
    cost: 200,
    img: require("@/components/common/img/alts/french(2).jpg"),
    description: {
      weight: "300g",
      material: "metal",
      manufacturer: "China",
      capacity: "5 cup",
    },
  },
  {
    id: 3,
    name: "french press",
    cost: 200,
    img: require("@/components/common/img/alts/french(3).jpg"),
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
    },
  },
  {
    id: 4,
    name: "french press",
    cost: 200,
    img: require("@/components/common/img/alts/french(4).jpg"),
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
    },
  },
  {
    id: 5,
    name: "french press",
    cost: 200,
    img: require("@/components/common/img/alts/french(5).jpg"),
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
    },
  },
  {
    id: 6,
    name: "french press",
    cost: 200,
    img: require("@/components/common/img/alts/french(6).jpg"),
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
    },
  },
  {
    id: 7,
    name: "french press",
    cost: 200,
    img: require("@/components/common/img/alts/french(7).jpg"),
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
    },
  },
  {
    id: 8,
    name: "french press",
    cost: 200,
    img: require("@/components/common/img/alts/french(8).jpg"),
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
    },
  },
  {
    id: 9,
    name: "french press",
    cost: 200,
    img: require("@/components/common/img/alts/french(9).jpg"),
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
    },
  },
  {
    id: 10,
    name: "french press",
    cost: 200,
    img: require("@/components/common/img/alts/french(10).jpg"),
    description: {
      weight: "300g",
      material: "glass",
      manufacturer: "USA",
      capacity: "4 cup",
    },
  },
  {
    id: 11,
    name: "french press",
    cost: 200,
    img: require("@/components/common/img/alts/french(11).jpg"),
  },
  {
    id: 12,
    name: "french press",
    cost: 200,
    img: require("@/components/common/img/alts/french(12).jpg"),
  },
  {
    id: 13,
    name: "Kermes",
    cost: 200,
    img: require("@/components/common/img/alts/kermes(1).png"),
  },
  {
    id: 14,
    name: "Kermes",
    cost: 200,
    img: require("@/components/common/img/alts/kermes(2).jpg"),
  },
  {
    id: 15,
    name: "Kermes",
    cost: 200,
    img: require("@/components/common/img/alts/kermes(3).png"),
  },
  {
    id: 16,
    name: "Kermes",
    cost: 200,
    img: require("@/components/common/img/alts/kermes(4).jpg"),
  },
  {
    id: 17,
    name: "purover",
    cost: 20,
    img: require("@/components/common/img/alts/purover(1).jpg"),
  },
  {
    id: 18,
    name: "purover",
    cost: 400,
    img: require("@/components/common/img/alts/purover(2).jpg"),
  },
  {
    id: 19,
    name: "purover",
    cost: 60,
    img: require("@/components/common/img/alts/purover(3).jpg"),
  },
  {
    id: 20,
    name: "purover",
    cost: 40,
    img: require("@/components/common/img/alts/purover(4).jpg"),
  },
  {
    id: 22,
    name: "purover",
    cost: 47,
    img: require("@/components/common/img/alts/purover(5).jpg"),
  },
];
